### ISSUE TITLE
how to use this zip on window

### ISSUE THREAD

**Issue by crashsol** [SjoerdNLD/coturn_cygwin_build#1]
how to config the turnserver.conf , my file is on c disk, there is  no /var/urs path

**Comment by SjoerdNLD** [comment]
Use like this example: userdb="C:\turnserver\db\turndb" or pidfile="C:\tmp\turnserver.pid"
Or put in the working directory, it will find it like this example: cert="contoso-crt.pem"
 or pkey="contoso-key.pem"
